
system_status_do_match_core: TRUE
system_status_do_match_contrib: TRUE
system_status_match_contrib_mode: FALSE
system_status_preg_match_contrib: "{^sites\/([A-z,\.,\-]+)\/modules\/contrib\/*}"
system_status_do_match_custom: FALSE
system_status_preg_match_custom : "{^sites\/([A-z,\.,\-]+)\/modules\/custom\/*}"
system_status_token: "Error-no-token"
system_status_encrypt_token: "Error-no-token"
system_status_service_allow_drupalstatus: 1
system_status_public_allow_public: 0
system_status_need_protect_token: 0
system_status_service_allow_drupalstatus: 1
system_status_token: ''
